// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVOVvXm_9c_SR5H2mAAXebfhf9jSMsp4U',
    appId: '1:521089895247:web:3d14ff20f3ea78b2dd533a',
    messagingSenderId: '521089895247',
    projectId: 'eval3-b15ba',
    authDomain: 'eval3-b15ba.firebaseapp.com',
    storageBucket: 'eval3-b15ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfVjz2Z4m081DcfpvMRSuz0zgSmYrVgGM',
    appId: '1:521089895247:android:ee614f0b4ec6bd54dd533a',
    messagingSenderId: '521089895247',
    projectId: 'eval3-b15ba',
    storageBucket: 'eval3-b15ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA2rCzAI8yBMiwoSrZiuKXpCrgdtkIXOk',
    appId: '1:521089895247:ios:4597ba497f10867edd533a',
    messagingSenderId: '521089895247',
    projectId: 'eval3-b15ba',
    storageBucket: 'eval3-b15ba.appspot.com',
    iosBundleId: 'com.johadaniel.shareprefrencesDsw22',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA2rCzAI8yBMiwoSrZiuKXpCrgdtkIXOk',
    appId: '1:521089895247:ios:cb4b2d47ac1b9a88dd533a',
    messagingSenderId: '521089895247',
    projectId: 'eval3-b15ba',
    storageBucket: 'eval3-b15ba.appspot.com',
    iosBundleId: 'com.johadaniel.shareprefrencesDsw22.RunnerTests',
  );
}
